version: "3.8"

services:
  agent:
    build:
      context: ./agent
    environment:
      BUILDKITE_AGENT_TOKEN: ${BUILDKITE_AGENT_TOKEN}
    volumes:
      - ~/.ssh/id_rsa-personal:/root/.ssh/id_rsa:ro