name: 'Simple'

on:
  workflow_dispatch:

jobs:
  simple:
    runs-on: 
      - "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List
        run: ls -R .