name: 'Simple'

on:
  repository_dispatch:
    types:
      - buildkite
jobs:
  simple:
    runs-on: 
      - "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List
        run: ls -R .